### ISSUE TITLE
adding spaces to the table won't work.

### ISSUE THREAD

**Issue by willie68** [saschaleib/dokuwiki-plugin-adhoctables#1]
Hi,
first of all, thanks for your work. On my website i have many tables integrated into the dokuwiki. So this plugin will save many hours of updating my site. But unfortunately, the whole thing doesn't work if you indent the tables with spaces. I like to do that for the sake of clarity. 
PS.: border="1" wont work, too...
a link to one of my pages using tables. [RCArduino: TPS](https://wkla.no-ip.biz/ArduinoWiki/doku.php?id=arduino:arduinosps&do=)

**Comment by willie68** [comment]
btw.: is there the possibility to use `<br/>` inside the cells, too?

**Comment by saschaleib** [comment]
Unfortunately, it seems like DokuWiki's automatisms are getting in your way here: DokuWiki interprets the indention as code block, and then just interprets all code that is inside the code block as, well, code :-)

There is not much I can do about that. It is really a limitation that comes from DokuWiki.

There is currently no support for `<br>` tags, because of course DokuWiki already has the ` \\ ` syntax that inserts these. If there is enough interest in these I might add them, but from my perspective, there are really very few use cases where you really need the tag over the DW syntax.

**Comment by willie68** [comment]
No problem. I found another plug in, which is working even with spaces in front.
htmlok, which will do the same as the original code. (As it is the original code)
